[package]
name = "mold-arch-arm32be"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "An internal crate of the mold linker, which instantiates it for arm32be"
license.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[dependencies]
libmold.workspace = true
